# SwiftLint Configuration for Modern macOS App Template
# Rules run by `swiftlint` command. Run `swiftlint rules` to print complete list.

included:
  - Sources
  - Tests

excluded:
  - Sources/Resources/Generated
  - .build
  - Packages
  - DerivedData

# Enabled rules
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - switch_case_alignment
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo
  - line_length

# Rule configurations
attributes:
  always_on_same_line:
    - "@IBAction"
    - "@IBOutlet"
    - "@NSManaged"
    - "@objc"

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  Modern macOS App Template
                    \/\/
                    \/\/  Created by .* on \d{1,2}\/\d{1,2}\/\d{4}\.
                    \/\/

force_cast: warning
force_try: warning
function_body_length:
  warning: 60
  error: 100

identifier_name:
  excluded:
    - id
    - url
    - uri

large_tuple:
  warning: 3
  error: 4

line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 5
    error: 10

type_body_length:
  warning: 300
  error: 400

type_name:
  excluded:
    - ID
    - URL
    - UUID

# Analyzer rules (require `swiftlint analyze`)
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import
